### ISSUE TITLE
Can't play on LAN

### ISSUE THREAD

**Issue by nudefireninja** [Fruktus/QuadradiusPreservationProject#37]
Greetings! Big thanks for putting all of this together!

I introduced my family to QR over Christmas and they liked it. 😄 We had to play hot seat style, which was good anyway because I was able to explain things easily, but in the future I would like to be able to host the server on my machine and have them join either via LAN or over the internet. The problem is that when I try to join the lobby from another machine, I get the connection error after the login.

I'm running it in Docker and on my local Mac it works fine. I have also tried it on a different Mac and locally it works, but when I try to connect from the other machine I either get a blank white screen before anything loads at all, or the login screen loads but then I can't see the other player in the lobby and get the error message instead.

I also tried hosting it on an Ubuntu machine, without success, so I don't think it's a macOS security issue (although I did try disabling the firewall there too).

Client side I have tried connecting with both the old Flash Player and Ruffle (desktop and browser extension). It works with neither, so they can probably be ruled out as the culprit.

I give up (for now). Is there anything you can think of? Any specific version of Linux or Ruffle that has worked for you that I could try?

Regards,
NFN

**Comment by ayush194** [comment]
On Mac, it works with Elmedia! You just need to tweak some settings in
preferences if you are using the M1 Mac.

**Comment by Fruktus** [comment]
Hi! Good job setting it up! Most likely this is a networking issue. Did you change the default ```127.0.0.1``` address? If not, the server is only listening on the local machine, and not allowing outside connections. Instructions to be added, I need to check how it works on mac :D

**Comment by Fruktus** [comment]
If possible, please add the exact command you have used to start the server 🙏

**Comment by kjarosh** [comment]
@nudefireninja Please make sure to use the `ADDRESS` environment variable to provide a reachable host/IP so that the client knows where to connect to. It is impossible to infer that value automatically, as the container may be reachable from various addresses.

For instance, if your local address is `192.168.0.111`, and other clients want to connect from the same network (`192.168.0.0/24`), you should use:
```
docker run -it \
  -p 3000:3000 \
  -p 3001:3001 \
  -p 8000:8000 \
  -e ADDRESS=192.168.0.111 \
  quadradius-server
```

The above will work as long as `192.168.0.111` is reachable from the client's perspective. You can also use your public IP so that people outside your network may join the server, provided your local computer and both ports are reachable.

README mentions this environment variable, but we should probably make it more obvious.

**Comment by nudefireninja** [comment]
Ah, it was just the `127.0.0.1` that needed to be changed! Basic mistake 😅 but thanks for helping me with it!

Now it works and I'm super happy!

Have a good day!

**Comment by Fruktus** [comment]
Glad it worked!
